language: python

services:
  - docker
dist: trusty

env:
  COMPOSE_VERSION: 18.06

install: docker-compose build

script:
  - docker-compose run --rm test-2.7
  - docker-compose run --rm test-3.3
  - docker-compose run --rm test-3.4
  - docker-compose run --rm test-3.5
  - docker-compose run --rm test-3.6
  - docker-compose run --rm test-3.7

after_script: docker-compose down
