language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

services:
  - docker
dist: trusty

env:
  COMPOSE_VERSION: 18.06

install: docker-compose build

script: docker-compose run --rm test

after_script: docker-compose down
