version: '2'
services:
  base:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app

  test:
    command: sh -c "./wait-for-redis.sh redis 6379 && ./wait-for-redis.sh redis-cluster 7000 && py.test"
    extends:
      service: base
    links:
      - redis
      - redis-cluster
    depends_on:
      - redis
      - redis-cluster

  redis:
    image: redis:latest

  redis-cluster:
    image: grokzen/redis-cluster:4.0.2
